name: Cross-language test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "Python/**"
      - "R/**"
      - "src/**"
      - "tests/cross_language/**"
      - ".github/workflows/cross_language_test.yaml"

jobs:
  test:
    name: cross-language test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up R 4.2.0
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.0

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          working-directory: R/

      - name: Install R package
        run: R CMD INSTALL R/

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "Python/ci-requirements.txt"

      - name: Install Python package
        run: |
          sudo apt-get install -y libarmadillo-dev
          python -m pip install Python/

      - name: Run cross-language test
        working-directory: tests/cross_language
        run: bash run.sh
        
